addons:
  sonarcloud:
    organization: "sanogotech"
    token:
      secure: "d981ff632ba8ef873b9cd96ebd10243f14cfca1b" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sanogotech_archijavajeespringboot
